# Generated by Django 4.0.5 on 2022-06-24 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mails',
            name='dt_stamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
