# Generated by Django 4.0.5 on 2022-06-25 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0002_mails_dt_stamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Backend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_host', models.CharField(blank=True, max_length=255, null=True)),
                ('email_host_user', models.CharField(blank=True, max_length=255, null=True)),
                ('email_host_password', models.CharField(blank=True, max_length=255, null=True)),
                ('email_port', models.CharField(blank=True, max_length=255, null=True)),
                ('email_use_tls', models.BooleanField(default=False)),
            ],
        ),
    ]
