# Generated by Django 4.0.5 on 2022-07-06 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0003_backend'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(blank=True, max_length=255, null=True)),
                ('url_slug', models.CharField(blank=True, max_length=255, null=True)),
                ('template_code', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
