# Generated by Django 4.0.5 on 2022-07-16 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0005_recipient_alter_mails_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='mails',
            name='res_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
