# Generated by Django 4.0.5 on 2022-07-17 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0007_alter_mailtemplate_url_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhishingLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='mails',
            old_name='res_id',
            new_name='unq_id',
        ),
        migrations.RenameField(
            model_name='recipient',
            old_name='res_id',
            new_name='unq_id',
        ),
        migrations.AddField(
            model_name='mails',
            name='recipients',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mailer.recipient'),
        ),
        migrations.AddField(
            model_name='mails',
            name='links',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mailer.phishinglink'),
        ),
    ]
