# Generated by Django 4.0.5 on 2022-07-17 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0008_phishinglink_rename_res_id_mails_unq_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhishingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('click_count', models.IntegerField(default=0)),
                ('data', models.TextField(blank=True, null=True)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailer.phishinglink')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailer.recipient')),
            ],
        ),
    ]
