# Generated by Django 4.0.5 on 2022-07-17 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0009_phishingdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mails',
            name='links',
        ),
        migrations.RemoveField(
            model_name='mails',
            name='recipients',
        ),
        migrations.AddField(
            model_name='phishinglink',
            name='mail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='links', to='mailer.mails'),
        ),
        migrations.AddField(
            model_name='recipient',
            name='mail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='mailer.mails'),
        ),
    ]
