# Generated by Django 4.0.5 on 2022-07-17 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0010_remove_mails_links_remove_mails_recipients_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhishingDataDict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='phishingdata',
            name='data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mailer.phishingdatadict'),
        ),
    ]
