# Generated by Django 4.0.5 on 2022-07-26 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0013_recipient_valid'),
    ]

    operations = [
        migrations.AddField(
            model_name='phishingdatadict',
            name='agent_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
